from os import path
configfile: "config/config.yaml"

fastq_to_fasta_interleave = srcdir("scripts/fastq-to-fasta-interleave.sh")
seq_count = srcdir("scripts/seq_count.py")
trans_6frame = srcdir("scripts/translate_6frames.py")

def get_read1(wildcards):
    return config["samples"][wildcards.sample_id][0]

def get_read2(wildcards):
    return config["samples"][wildcards.sample_id][1]
    
def getMean(wildcard):
    est_path = "{}/last_alignments/{}.frag_len_est".format(config["out_dir"],wildcard)
    if(path.exists(est_path)):
	    with open(est_path) as f:
	    	for line in f:
	    		if line.startswith("# estimated mean distance"):
	    			return(line.rstrip().split()[-1])
    else:
    	return(-1)

def getSTD(wildcard):
    est_path = "{}/last_alignments/{}.frag_len_est".format(config["out_dir"],wildcard)
    if(path.exists(est_path)):
	    with open(est_path) as f:
	    	for line in f:
    			if line.startswith("# estimated standard deviation of distance"):
		    		return(line.rstrip().split()[-1])
    else:
    	return(-1)

rule all:
    input:
        [
            expand(config["out_dir"]+"last_counts/{sample_id}/{sample_id}.counts",sample_id=config["samples"].keys())
        ]
	
rule last_db:
    input:
        reference = config["reference_p"]
    output:
       touch(config["out_dir"]+'last_index/index.done')
    params:
       index_basename="{0}/last_index/index".format(config["out_dir"])
    conda:
    	"env/last.yaml"       
    shell:
       "lastdb -p {params.index_basename} {input.reference}"
       #"lastdb {params.index_basename} {input.reference}"

rule last_scoring:
    input:
    	reference_flag = config["out_dir"]+"last_index/index.done",
	query = config["samples"][list(config["samples"].keys())[0]][0],
    params:
        last_index_basename="{0}/last_index/index".format(config["out_dir"]),
        last_sample1="{0}/last_sample/sample_1.sample.fa".format(config["out_dir"]),
        last_trans_sample1="{0}/last_sample/translated.sample_1.sample.fa".format(config["out_dir"]),
    output:
    	config["out_dir"]+"last_sample/scoring_scheme"
    conda:
    	"env/lastxpy.yaml"
    shell:
    	"""
    	head -n 400000 {input.query} > {params.last_sample1}
    	python {trans_6frame} {params.last_sample1}  {params.last_trans_sample1}
    	last-train --revsym --matsym --gapsym --sample-number=600000 -S0 {params.last_index_basename} {params.last_trans_sample1}> {output}
	"""
rule last_frag_stat_est:
    input:
        reference_flag = config["out_dir"]+"last_index/index.done",
        reads1 = get_read1,
        reads2 = get_read2,
        scoring = config["out_dir"]+"last_sample/scoring_scheme",
    params:
        last_index_basename="{0}/last_index/index".format(config["out_dir"]),
        last_al = "{0}/last_alignments".format(config["out_dir"]),
    output :
        frag_len_est=config["out_dir"]+"last_alignments/{sample_id}.frag_len_est",
    conda:
    	"env/last.yaml"
    shell:
        """
        mkfifo {params.last_al}/{wildcards.sample_id}_1
        mkfifo {params.last_al}/{wildcards.sample_id}_2
        gzip -cdf {input.reads1} | head -n 400000 > {params.last_al}/{wildcards.sample_id}_1 &
        gzip -cdf {input.reads2} | head -n 400000 > {params.last_al}/{wildcards.sample_id}_2 &
        {fastq_to_fasta_interleave} {params.last_al}/{wildcards.sample_id}_1 {params.last_al}/{wildcards.sample_id}_2 | lastal -i1 -p {input.scoring} -F15 {params.last_index_basename} | last-pair-probs -e > {output.frag_len_est}
        rm {params.last_al}/{wildcards.sample_id}_1 {params.last_al}/{wildcards.sample_id}_2
        """
	
rule align_last:
    input:
        reference_flag = config["out_dir"]+"last_index/index.done",
        reads1 = get_read1,
        reads2 = get_read2,
        frag_len_est= config["out_dir"]+"last_alignments/{sample_id}.frag_len_est",
        scoring = config["out_dir"]+"last_sample/scoring_scheme",
    params:
        last_index_basename="{0}/last_index/index".format(config["out_dir"]),
        mean = getMean,
        std = getSTD,
    threads: workflow.cores/len(config["samples"])
    output:
        config["out_dir"]+"last_alignments/{sample_id}.tab"
    conda:
    	"env/lastal.yaml"
    shell:
        "{fastq_to_fasta_interleave} {input.reads1} {input.reads2} | "
        "parallel --gnu --pipe -L4 -j {threads} 'lastal -i1 -p {input.scoring} -F20 {params.last_index_basename}' |"
        "last-pair-probs -f {params.mean} -s {params.std} -m 0.95 -d 0.1 |"
        "maf-convert tab > {output}"
rule count_last:
    input:
        alignments = config["out_dir"]+"last_alignments/{sample_id}.tab",
        reference = config["reference_p"]
    params:
    	mean = getMean,
    	std = getSTD,
    output:
        config["out_dir"]+"last_counts/{sample_id}/{sample_id}.counts"
    conda:
    	"env/counting.yaml"
    shell:
        "python {seq_count} {input.alignments} {output} --frag_len_mean {params.mean} --frag_len_std {params.std} --reference {input.reference}"
        
